.github(workflows): pin Nim stable versions at 1.6.8 and 1.0.10
exercism/nim pull request #432
Opened 2022-10-28 15:11 UTC by ee7

Pin the stable Nim versions that we use, rather than always using the latest release on the 1.6 and 1.0 branches.

Nim 1.6.8 and 1.0.10 are the latest tags on their respective branches, as shown by this list of the most recent tags, in reverse chronological order:

| Date       | Tag    |
| ---------  | ------ |
| 2022-09-27 | 1.6.8  |
| 2022-05-05 | 1.6.6  |
| 2022-02-09 | 1.2.18 |
| 2022-02-09 | 1.6.4  |
| 2021-12-17 | 1.6.2  |
| 2021-12-16 | 1.2.16 |
| 2021-12-03 | 1.2.14 |
| 2021-10-19 | 1.6.0  |
| 2021-05-25 | 1.4.8  |
| 2021-04-15 | 1.4.6  |
| 2021-04-15 | 1.2.12 |
| 2021-02-23 | 1.2.10 |
| 2021-02-23 | 1.4.4  |
| 2020-12-01 | 1.4.2  |
| 2020-10-27 | 1.2.8  |
| 2020-10-27 | 1.0.10 |

For more information, see the release blog posts for [1.6.8](https://nim-lang.org/blog/2022/09/27/version-168-released.html) and [1.1.10](https://nim-lang.org/blog/2020/10/27/versions-128-and-1010-released.html) 

Closes: #427

2022-10-30 14:32 UTC, ynfle requested changes

2022-10-30 14:32 UTC, ynfle commented on .github/workflows/exercises.yml
> +          version: "binary:${{ matrix.nim == 'stable' && '1.6.8' || matrix.nim }}"
I think this should instead be specified as 1.6.8 and referred to as stable. It's not clear that this doesn't get updated when there is a new stable release. That fact is hidden from the matrix definition

2022-10-31 07:36 UTC, ErikSchierboom approved these changes

2022-10-31 13:28 UTC, ynfle approved these changes
Looks great. Regarding code duplication, you could make it a variable for the whole file and reuse it. 🤷. Definitely non-blocking. I think there are ways to do that.

2022-10-31 20:15 UTC, merged

2022-10-31 23:56 UTC, ynfle commented
Sounds good