exercises(allergies): overhaul to use `enum`
exercism/nim pull request #434
Opened 2022-10-29 15:34 UTC by ee7

Closes: #404

2022-10-30 14:38 UTC, ynfle requested changes

2022-10-30 14:38 UTC, ynfle commented on exercises/practice/allergies/.meta/example.nim
> +func isAllergicTo*(allergen: Allergen, score: int): bool =
I think the arguments here should be flipped because it is asking given a score, are they allergic to an allergen

2022-10-30 14:38 UTC, ynfle commented on exercises/practice/allergies/.meta/example.nim
> +  (score and 1 shl allergen.ord) != 0
I think we should use `bitops.testbit` here

2022-10-31 13:36 UTC, ynfle commented on exercises/practice/allergies/.meta/example.nim
> +  (score and 1 shl allergen.ord) != 0
I agree in the other 2 situations, but here, IMO, it's different. The point over here is to realize that you can just test the bit. I don't see it relevant in knowing how to test the bit with `and` or `shift`s. It still reveals an understanding of the fundamentals of the exercise and concepts.

Definitely non-blocking as its not user-facing code.

2022-11-10 03:42 UTC, ynfle commented on exercises/practice/allergies/.meta/example.nim
> +  (score and 1 shl allergen.ord) != 0
I will still argue that `testBit` already encompasses the heart of the exercise. That shift is core. Either way I'm approving. I see your point

2022-11-10 03:43 UTC, ynfle approved these changes
🚀

2022-12-04 09:50 UTC, kytrinyx commented
This PR is approved. @ee7 do you have any qualms about merging it?

2023-01-11 10:57 UTC, merged